name: Send Pending Chapter Notifications

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  send-notifications:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification request
        run: |
          curl -X POST "${{ secrets.API_BASE_URL }}/push/send-pending-notifications" \
          -H "X-API-Key: ${{ secrets.API_KEY }}"