name: Send Pending Chapter Notifications

on:
  schedule:
    # Runs every 2 minutes
    - cron: '*/2 * * * *'
  workflow_dispatch:

jobs:
  send-notifications:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification request
        run: |
          curl -X POST "${{ secrets.API_BASE_URL }}/push/send-pending-notifications" \
          -H "X-Push-Noti-Key: ${{ secrets.PUSH_NOTI_KEY }}"